site_name: BI-SWI Wiki
site_url: https://Dzendys.github.io/swi_wiki
repo_name: Dzendys/swi_wiki
repo_url: https://github.com/Dzendys/swi_wiki
theme:
  name: material
  custom_dir: overrides
  language: cs
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.expand
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
      primary: indigo
      accent: indigo
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
      primary: indigo
      accent: indigo

docs_dir: wiki

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - tables
  - toc
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

plugins:
  - search
  - obsidian-bridge
  - awesome-pages:
      collapse_single_pages: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  analytics:
    provider: custom

